---
- name: Lockdown SSH
  hosts: vps
  become: yes
  tasks:
    - name: Disable Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Disable Password Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    # Opcjonalne: Wyłączenie ChallengeResponse (często domyślnie 'yes' na Ubuntu)
    - name: Disable Challenge Response Auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'
        state: present

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
