---
- name: Setup Ruby on Mikrus VPS
  hosts: vps
  vars:
    user_name: "wdek"
    user_home: "/home/{{ user_name }}"

  tasks:
    - name: Check if Ruby is installed via mise
      shell: "~/.local/bin/mise x ruby -- ruby -v"
      register: ruby_check
      ignore_errors: yes
      changed_when: false

    - name: Install Latest Ruby using mise (ASYNC - High Timeout for Mikrus)
      shell: "~/.local/bin/mise use --global ruby@latest"
      become: yes
      become_user: "{{ user_name }}"
      async: 3600  # Czekamy max godzinę
      poll: 60     # Sprawdzamy co minutę
      when: ruby_check.rc != 0

    - name: Install Rails gem using mise
      shell: |
        export PATH="$HOME/.local/bin:$PATH"
        mise x ruby -- gem install rails
      become: yes
      become_user: "{{ user_name }}"
