---
- name: Setup Ruby on Mikrus VPS
  hosts: vps
  vars:
    user_name: "wdek"
    user_home: "/home/{{ user_name }}"
    asdf_dir: "{{ user_home }}/.asdf"

  tasks:
    - name: Add Ruby plugin to ASDF
      shell: |
        export ASDF_DIR="{{ asdf_dir }}"
        . "{{ asdf_dir }}/asdf.sh"
        asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
      args:
        creates: "{{ asdf_dir }}/plugins/ruby"
      become: yes
      become_user: "{{ user_name }}"

    - name: Install Latest Ruby (ASYNC - High Timeout for Mikrus)
      shell: |
        export ASDF_DIR="{{ asdf_dir }}"
        . "{{ asdf_dir }}/asdf.sh"
        asdf install ruby latest
        asdf global ruby latest
      become: yes
      become_user: "{{ user_name }}"
      async: 3600  # Czekamy max godzinę
      poll: 60     # Sprawdzamy co minutę

    - name: Install Rails gem
      shell: |
        export ASDF_DIR="{{ asdf_dir }}"
        . "{{ asdf_dir }}/asdf.sh"
        gem install rails
      become: yes
      become_user: "{{ user_name }}"
