---
- name: Setup Mikrus VPS
  hosts: vps
  vars:
    user_name: "wdek"
    user_home: "/home/{{ user_name }}"
    asdf_dir: "{{ user_home }}/.asdf"
    # Pamiętaj, żeby podać --ask-vault-pass przy uruchamianiu playbooka
    ssh_backup_file: "ssh_backup.tar.gz"

  tasks:
    - name: Update apt cache and install dependencies
      apt:
        update_cache: yes
        name:
          - git
          - curl
          - wget
          - zsh
          - unzip
          - build-essential
          - libssl-dev
          - libreadline-dev
          - zlib1g-dev
          - software-properties-common
          - docker.io  # Potrzebne, żeby istniała grupa docker
          - stow
          - ripgrep
          - fd-find
          - bat
          - tmux
          - fzf
          - ncdu
          - jq
          - httpie
          - btop
          - eza # Now available in Ubuntu 24.04 apt repos
        state: present

    - name: Symlink fd-find to fd
      file:
        src: /usr/bin/fdfind
        dest: /usr/local/bin/fd
        state: link
        force: yes

    - name: Symlink batcat to bat
      file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
        force: yes

    - name: Add Neovim PPA (unstable)
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present

    - name: Install Neovim
      apt:
        name: neovim
        state: latest

    - name: Install zoxide
      apt:
        name: zoxide
        state: present

    # --- GitHub CLI Setup ---
    - name: Download GitHub CLI GPG key
      get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
        mode: '0644'

    - name: Add GitHub CLI repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        state: present
        filename: github-cli

    - name: Install GitHub CLI
      apt:
        name: gh
        state: latest
        update_cache: yes

    # --- LazyGit Setup ---
    - name: Install LazyGit
      shell: |
        LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
        curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
        tar xf lazygit.tar.gz lazygit
        install lazygit /usr/local/bin
        rm lazygit lazygit.tar.gz
      args:
        creates: /usr/local/bin/lazygit

    # --- YQ Setup ---
    - name: Install yq
      get_url:
        url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        dest: /usr/local/bin/yq
        mode: '0755'

    - name: Create user {{ user_name }}
      user:
        name: "{{ user_name }}"
        shell: /bin/zsh
        groups: sudo,docker
        append: yes
        state: present

    - name: Enable passwordless sudo for {{ user_name }}
      lineinfile:
        path: /etc/sudoers.d/{{ user_name }}
        line: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Configure Docker Log Rotation (Critical for Mikrus)
      copy:
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
        dest: /etc/docker/daemon.json
      notify: Restart Docker

    - name: Copy local .tmux.conf
      copy:
        src: .tmux.conf
        dest: "{{ user_home }}/.tmux.conf"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Copy decrypted SSH backup to server
      copy:
        src: "{{ ssh_backup_file }}"
        dest: "{{ user_home }}/{{ ssh_backup_file }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'

    - name: Ensure .ssh directory exists
      file:
        path: "{{ user_home }}/.ssh"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0700'

    - name: Extract SSH keys
      unarchive:
        src: "{{ user_home }}/{{ ssh_backup_file }}"
        dest: "{{ user_home }}/"
        remote_src: yes
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Fix SSH permissions (files)
      shell: "chmod 600 {{ user_home }}/.ssh/*"
      # Ignorujemy błędy, jeśli katalog jest pusty, ale po rozpakowaniu nie powinien być
      ignore_errors: yes

    - name: Fix SSH permissions (directory)
      file:
        path: "{{ user_home }}/.ssh"
        mode: '0700'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Ensure dotfiles directory structure for Stow
      file:
        path: "{{ user_home }}/dot/lazy/.config"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes

    - name: Clone LazyVim starter
      git:
        repo: https://github.com/LazyVim/starter.git
        dest: "{{ user_home }}/dot/lazy/.config/nvim"
      become: yes
      become_user: "{{ user_name }}"

    - name: Ensure target .config directory exists
      file:
        path: "{{ user_home }}/.config"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Remove existing .config/nvim (to allow Stow)
      file:
        path: "{{ user_home }}/.config/nvim"
        state: absent

    - name: Stow LazyVim
      shell: "stow -v -d {{ user_home }}/dot -t {{ user_home }} lazy"
      become: yes
      become_user: "{{ user_name }}"
      register: stow_result
      changed_when: "'LINK' in stow_result.stderr"

    - name: Install Oh-My-Zsh (unattended)
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: "{{ user_home }}/.oh-my-zsh"
      become: yes
      become_user: "{{ user_name }}"

    - name: Ensure ASDF directory ownership
      file:
        path: "{{ asdf_dir }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes

    - name: Clone ASDF
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "{{ asdf_dir }}"
        version: v0.14.0
      become: yes
      become_user: "{{ user_name }}"

    - name: Add ASDF to .zshrc
      lineinfile:
        path: "{{ user_home }}/.zshrc"
        line: '. "$HOME/.asdf/asdf.sh"'
        create: yes
        owner: "{{ user_name }}"

    - name: Add Nodejs plugin to ASDF
      shell: |
        export ASDF_DIR="{{ asdf_dir }}"
        . "{{ asdf_dir }}/asdf.sh"
        asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
      args:
        creates: "{{ asdf_dir }}/plugins/nodejs"
      become: yes
      become_user: "{{ user_name }}"

    - name: Install Latest Nodejs
      shell: |
        export ASDF_DIR="{{ asdf_dir }}"
        . "{{ asdf_dir }}/asdf.sh"
        asdf install nodejs latest
        asdf global nodejs latest
      become: yes
      become_user: "{{ user_name }}"

    - name: Install AI CLI Tools (Claude Code, Gemini CLI)
      shell: |
        export ASDF_DIR="{{ asdf_dir }}"
        . "{{ asdf_dir }}/asdf.sh"
        npm install -g @anthropic-ai/claude-code @google/gemini-cli
      become: yes
      become_user: "{{ user_name }}"

    - name: Configure Git Global User Name
      git_config:
        name: user.name
        scope: global
        value: "Michal Danieluk"
      become: yes
      become_user: "{{ user_name }}"

    - name: Configure Git Global Email
      git_config:
        name: user.email
        scope: global
        value: "michal.danieluk@gmail.com"
      become: yes
      become_user: "{{ user_name }}"

    - name: Test GitHub SSH Connection
      shell: "ssh -T git@github.com"
      become: yes
      become_user: "{{ user_name }}"
      register: github_ssh_test
      ignore_errors: yes
      changed_when: false

    - name: Display GitHub Connection Status
      debug:
        msg: "{{ 'GitHub Connection Successful!' if 'successfully authenticated' in github_ssh_test.stderr else 'GitHub Connection FAILED! Check SSH keys.' }}"

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted

